version: "3"
services:
  mariadb:
    build:
      dockerfile: DockerFile
    container_name: mdb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: 123456789
    volumes:
      - C:\Dockerfile\db-on-docker-ms:/var/lib/mariadb
    networks:
      - backend

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  haproxy:
    image: haproxy:alpine
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"
    volumes:
      - ./templates/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - backend

  app1:
    container_name: server1
    build:
      dockerfile: DockerFile_app1
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    environment:
        DB_URL: jdbc:mariadb://mdb:3306/cfd
    networks: 
      - backend

  app2:
    container_name: server2
    build:
      dockerfile: DockerFile_app2
    ports:
      - 8082:8080
    depends_on:
      - mariadb
    environment:
        DB_URL: jdbc:mariadb://mdb:3306/cfd
    networks: 
      - backend

networks:
  backend:
    driver: bridge